# Site settings
title: babita shekhawat
email: babitashekhawat30aug@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.babitashekhawat.me" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
